//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Details
    {
        public Client_Details()
        {
            this.Client_Invoice = new HashSet<Client_Invoice>();
        }
    
        public int Id { get; set; }
        public string AY { get; set; }
        public int ClientId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<Client_Invoice> Client_Invoice { get; set; }
    }
}
