//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Client_Details = new HashSet<Client_Details>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PinCode { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public int ReturnTypeId { get; set; }
        public string PAN { get; set; }
        public string GST { get; set; }
        public string DOB { get; set; }
    
        public virtual ReturnType ReturnType { get; set; }
        public virtual ICollection<Client_Details> Client_Details { get; set; }
    }
}
