//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Invoice
    {
        public int Id { get; set; }
        public Nullable<int> Client_Id { get; set; }
        public string InvoiceNumber { get; set; }
        public int Client_DetailsId { get; set; }
    
        public virtual Client_Details Client_Details { get; set; }
    }
}
