//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EDMX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JSPEntities : DbContext
    {
        public JSPEntities()
            : base("name=JSPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Client_Details> Client_Details { get; set; }
        public DbSet<Client_Invoice> Client_Invoice { get; set; }
        public DbSet<Client> Clients { get; set; }
        public DbSet<Company_Details> Company_Details { get; set; }
        public DbSet<Login> Logins { get; set; }
        public DbSet<ReturnType> ReturnTypes { get; set; }
    }
}
